name:                catln
version:             0.1.0.0
github:              "zachgk/catln"
license:             MIT
author:              "Zach Kimberg"
maintainer:          "zachary@kimberg.com"
copyright:           "2019 Zach Kimberg"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zachgk/catln#readme>

default-extensions:
- OverloadedStrings
- TupleSections
- NamedFieldPuns

# Deps from stackage - https://www.stackage.org/lts-18.28
dependencies:
- base
- mtl
- haskeline
- containers
  # - llvm-hs==0.9.0.1
  # - llvm-hs-pure==9.0.1
- directory
- bytestring
- utf8-string
- megaparsec
- text
- parser-combinators
- haskeline
- unordered-containers
- transformers
- split
- hspec
- tasty
- tasty-hunit
- hashable
- pretty-simple
- tuple
- semialign
- aeson
- scotty
- optparse-applicative
- wai-middleware-static
- stringbuilder
- pandoc
- pandoc-types
- tree-sitter
- tree-sitter-haskell
- tree-sitter-python

library:
  source-dirs: src

executables:
  catln:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      # - -threaded
      # - -rtsopts
      # - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - catln

tests:
  catln-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      # - -threaded
      # - -rtsopts
      # - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - catln
