name: continuous

on:
  push:
    paths:
      - "**.hs"
      - "webdocs/**"
  pull_request:
    paths:
      - "**.hs"
      - "webdocs/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-global-
      - uses: actions/cache@v4
        name: Cache .stack-work
        with:
          path: .stack-work
          key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('**/*.hs') }}
          restore-keys: |
            ${{ runner.os }}-stack-work-
      - uses: haskell-actions/setup@v2
        with:
          enable-stack: true
      - run: stack test --pedantic

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: webdocs/package-lock.json
      - run: cd webdocs && npm ci
      - run: cd webdocs && npm run test:run
      - run: cd webdocs && npm run test:integration:full
